### ISSUE TITLE
2-5にDBマイグレータ実行コマンド部分を追加する

### ISSUE THREAD

**Issue by IKD-104** [team-lab/skillup#39]
スキルアップ1回目に「Userテーブルがなくて接続できない」との報告があり

１ LaravelはチュートリアルのためにデフォルトでUserモデルとマイグレータファイルを用意してくれている。
２ DBの連携関係はユーザの設定に依存するので、DBのテーブル作成はユーザが手動で実行するしかない
３ このためテーブルがなく、エラーが発生した

って感じっぽいです。

なので２−３に
```
docker-compose exec workspace bash
php artisan migrate
```
を実行するって文言を追記してもらいたい感じです。

**Comment by grandcolline** [comment]
こちら上記のPRで対応していただき、本番確認も取れましたので、クローズします。
