### ISSUE TITLE
STEP2 テスト項目

### ISSUE THREAD

**Issue by nazoking** [team-lab/skillup#6]
- トップ画面
  - [ ] クリックするとTODOリストを作成する
  - [ ] メッセージ表示
  - [ ] 三〇文字以上ならエラーメッセージ表示でリストが作成されない
  - [ ] 〇文字ならエラーメッセージ表示でリストが作成されない
  - [ ] <>&" などの特殊文字の扱いが適切である
  - [ ] リスト名表示
  - [ ] 「{TODO数}個中{完了したTODO数}個がチェック済み」表示
  - [ ] 一番古いTODOの締め切りを表示する
  - [ ] 新しいTODOリストが挿入されている
  - [ ] リストが新しく作られた順に表示する
  - [ ] リストの名前をクリックすると、そのリストのTODO画面に遷移する
- ToDo詳細画面
  - [ ] ToDoリストの名前を表示
  - [ ] クリックするとTODOを作成する
  - [ ] TODOの名前表示
  - [ ] 期限の日次表示
  - [ ] 作成した日時表示
  - [ ] 完了か未完了かの状態表示
  - [ ] ToDoの追加ボタンを押すと、新しいToDoが挿入される。
  - [ ] ToDoの作成した日次が新しい順に上から表示
  - [ ] デフォルトの状態は未完了
  - [ ] 完了未完了ボタンで状態が反転する
  - [ ] ToDo名が空の場合はエラーを表示する
- 検索画面
  - [ ] 検索ボタンをクリックするとajaxで検索を開始する
  - [ ] 表示順はToDoの作成日が新しい順
  - [ ] ToDoの名前が表示される
  - [ ] そのToDoのリストの名前が表示される
  - [ ] ToDoの期限が表示される
  - [ ] ToDoの作成した日が表示される
  - [ ] クリックすると対象のToDoがあるToDoリストの画面（ToDo画面)に遷移
- 共通ヘッダー
  - [ ] ロゴをクリックするとトップ画面に遷移する
  - [ ] 検索画面へのリンク

**Comment by nazoking** [comment]
仕様書の修正
　一番古いTODOの締め切り　 →　リスト内の未完了のTODOの期限の内一番古い日付をさすもの
　<>&" などの特殊文字の扱い　→　エスケープされること
　期限日のフォーマット、バリデーション、未入力の場合の扱い

**Comment by arktks** [comment]
古いから削除
