### ISSUE TITLE
【🔥】画像アップロード問題

### ISSUE THREAD

**Issue by takahiro9** [team-lab/skillup#62]
## 問題

+ [常識2. Dynoにファイルアップロードしても再起動時に消える](https://blog.mah-lab.com/2013/05/16/heroku-commons-16/)
    + ので、現状のカリキュラムだと、アプリケーションサーバにファイル置くので消えてしまう。
    + 画像見れない

## 取りうる選択肢

+ インスタやめる
    + とはいえ画像あげたくなる人は出現しそう

+ 手間のかからないクラウドストレージサービスの洗濯
    + こっちでクレカ登録とかしたくない

+ そもそも heroku から変更してみる。

+ カリキュラムに但し書きして置く（1時間で消えちゃうと思うけどきおつけてね）
    + メッッチャ楽

**Comment by itayayuichiro** [comment]
画像自体をbase64でencodeしてDBに格納するというのはどうですか？

**Comment by IKD-104** [comment]
> DB
一つの手段ではあるのですが、Webサービスとしてはあまりない手段で、外から批判も出そうな気もするのですよね。。。
なので、S3に上げる方法で記事を書き換えるのが、現在の最善？

**Comment by IKD-104** [comment]
こちらの話を有川さんと先ほど話ました。
その結果「そこまでDBに保存するの変というわけではないんじゃない？」ということで、自分の感覚の偏りで勝手に決めているっぽかったです。すみません！！

* 画像投稿の説明部分はとりあえず現在のままの記載で行く
* Herokuの但し書きとして「DBでバイナリ保存にせざるを得ないからこうやってね」という記載を追加
* 可能であれば、LocalではStrage保存、HerokuではDB保存という出しわけを.env設定でできるような記述を追加したい

という話をしました。

@grandcolline @ikedanatsuko @takahiro9 @ishizukayusuke 
もし、この方針で良いようでしたら、 @itayayuichiro くんにこの方法ができるかをまず確認してもらい、記述を修正していきたいと思うのですが、どうでしょうか？

**Comment by grandcolline** [comment]
いいと思います！
ただ、考えられる問題点は、herokuの無料枠のDBの容量が5MBっぽいってことでしょうかね？

**Comment by itayayuichiro** [comment]
大丈夫です！

一旦自分の手で実装して、herokuにデプロイして画像表示するところまでやります。

**Comment by itayayuichiro** [comment]
@grandcolline さん
自分のbase64で保存する方法でherokuデプロイ＆動作確認してました。
一応できましたー

http://skillup-itaya.herokuapp.com/

※画像投稿以外の機能をまともに実装してないので、テストする際は大目に見てください...

**Comment by itayayuichiro** [comment]
記述修正についてなのですが、画像のアップロードから表示までセットで記述すべきだと考えているのですが、あまり書きすぎてしまうと課題の答えになりすぎてしまう気がしていて...

書くとしたらどのセクションに書くのが良いでしょうか？

**Comment by grandcolline** [comment]
@itayayuichiro 

遅くなってしまってごめんなさい。
一旦は、出していただいたPRで構わないかと思います。

ただ、個人的には、[STEP2.7](https://team-lab.github.io/skillup/step2/07-upload.html)から、DBに入れるように書き換えてしまっても良い気がします。
ここは他の方の意見も聞いてみたいですねぇ

**Comment by grandcolline** [comment]
@itayayuichiro 

- 2-9でDB設計の注意書きを入れる
- 2-11で画像が上がらなくても大丈夫である旨、上げる方法のリンクをついき
