### ISSUE TITLE
STEP1-6.PHPでGET,POSTを受け取るのサンプルが誤っている

### ISSUE THREAD

**Issue by morishitashigeya** [team-lab/skillup#7]
`<?php
      //commentがPOSTされているなら
      if(isset($_POST["comment"])){
        //エスケープしてから表示
        $comment = htmlspecialchars($_POST["comment"]);
        print("あなたのコメントは「 ${comment} 」です。");
      } else {
    ?>`
else{でシンタックスエラー

**Comment by arktks** [comment]
古いから削除
